# Generated by Django 3.2.9 on 2022-01-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='')),
                ('product_name', models.CharField(max_length=500)),
                ('product_price', models.IntegerField()),
                ('product_category', models.CharField(choices=[('t', 'Top Wear'), ('B', 'Bottom Wear'), ('F', 'Foot Wear')], max_length=1)),
                ('product_description', models.CharField(max_length=500)),
                ('product_discount', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
